apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blitzmine-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/websocket-services: blitzmine-backend
spec:
  ingressClassName: nginx
  rules:
    - host: api.blitzmine.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blitzmine-backend
                port:
                  number: 80
