[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
blitzmine = "CVud2PiM4hYk2YkDa2DZ2dnJwd9gVCXZFJP18DzE1r4F"

[programs.devnet]
blitzmine = "CVud2PiM4hYk2YkDa2DZ2dnJwd9gVCXZFJP18DzE1r4F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run test"
